version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    # For each dependencies group, dependabot will open a PR containing
    # the new versions available for that group.
    groups:
      # all dependencies group
      all-dependencies:
        patterns:
        - "arboard"
        - "async-trait"
        - "bincode"
        - "blas-src"
        - "bytemuck"
        - "candle-core"
        - "clap"
        - "console_error_panic_hook"
        - "crossterm"
        - "csv"
        - "dashmap"
        - "derive-new"
        - "dirs"
        - "fake"
        - "flate2"
        - "float-cmp"
        - "futures-intrusive"
        - "getrandom"
        - "github-device-flow"
        - "gix-tempfile"
        - "globwalk"
        - "half"
        - "hashbrown"
        - "hound"
        - "image"
        - "indicatif"
        - "js-sys"
        - "libc"
        - "libm"
        - "log"
        - "matrixmultiply"
        - "md5"
        - "ndarray"
        - "num-traits"
        - "nvml-wrapper"
        - "openblas-src"
        - "pollster"
        - "pretty_assertions"
        - "proc-macro2"
        - "protobuf"
        - "protobuf-codegen"
        - "quote"
        - "r2d2"
        - "r2d2_sqlite"
        - "rand"
        - "rand_distr"
        - "ratatui"
        - "rayon"
        - "regex"
        - "reqwest"
        - "rmp-serde"
        - "rstest"
        - "rusqlite"
        - "rust-format"
        - "sanitize-filename"
        - "serde"
        - "serde-wasm-bindgen"
        - "serde_json"
        - "serde_rusqlite"
        - "serial_test"
        - "spin"
        - "strum"
        - "strum_macros"
        - "syn"
        - "sysinfo"
        - "systemstat"
        - "tch"
        - "tempfile"
        - "text_placeholder"
        - "thiserror"
        - "tokio"
        - "tracing-appender"
        - "tracing-core"
        - "tracing-subscriber"
        - "uuid"
        - "wasm-bindgen"
        - "wasm-bindgen-futures"
        - "wasm-logger"
        - "wasm-timer"
        - "web-time"
        - "wgpu"
